pipeline {
    agent any

    tools {
        maven 'MavenLab'
    }
    
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Build Application') {
            steps {
                dir('starter') {
                    sh 'mvn -B clean package'
                }
            }
        }
        stage('Build Image') {
            steps {
                sh 'docker build -t team-skeleton -f starter/Dockerfile .'
            }
        }
        stage('Smoke Test') {
            steps {
                sh 'docker run --rm team-skeleton'
            }
        }
    }
}
